feat(vwc-inline): add more inline size options
Vonage/vivid pull request #1053
Opened 2021-09-05 10:32 UTC by rinaok

## Description

## Motivation and Context

### All Submissions:
* [ ] I followed the guidelines in our [Contributing document](https://github.com/orgs/Vonage/teams/vivid-core/discussions/2)?
* [ ] My code follows the code style of this project
* [ ] I checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Screenshots (if appropriate):

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

* [ ] A11y tests
* [ ] Ui tests
* [ ] Unit and coverage
* [ ] Test for Aria [matching roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)
* [ ] [Check the markup](https://validator.w3.org/)
* [ ] [Custom Control Accessible Development Checklist](https://w3c.github.io/using-aria/#checklist)
* [ ] Check unused/missing dependencies

## Checklist:

* [ ] API Changes are documented in code and exported accordingly ([JSDoc](https://jsdoc.app/about-getting-started.html))

2021-09-30 14:30 UTC, rinaok commented
@yinonov Should we change the name to vwc-layout now? Or later?

2021-10-03 07:44 UTC, yinonov commented
> @yinonov Should we change the name to vwc-layout now? Or later?

add another PR, just to have clear comparison for review

2021-10-03 08:46 UTC, yinonov requested changes

2021-10-03 08:46 UTC, yinonov commented on components/inline/readme.md
> +| `template`      | `template`       | `"fill" \| "fit"`                 | undefined | Sets the initial preferred template from predefined available options            |
what do you think of `Auto-Sizing`? is it a better name? template is too generic in the grid sense

2021-10-03 08:46 UTC, yinonov commented on components/inline/src/vwc-inline.scss
> +	'xl': 32px
```suggestion
	xs: 16px,
	md: 24px,
	xl: 32px
```

2021-10-03 08:46 UTC, yinonov commented on components/inline/src/vwc-inline.scss
> +);
same as `$items-spacings` so why not keeping a common var? it's local only

2021-10-03 08:46 UTC, yinonov commented on components/inline/src/vwc-inline.scss
> +	.layout {
there's a lot of repetitive `.layout` selector.
in sass u can parent select
e.g.
```css
.layout {
  :host(:not(template)) &,
  :host([template="fit"i]) & {
    #{$inline-template}: auto-fit;
  }
  // ... and all other parent selectors
}
```

2021-10-03 08:46 UTC, yinonov commented on components/inline/test/inline.test.js
> +				columnBasis: 'sm', columnSpacing: 'md', inlineGutters: 'md'
are we checking properties attributes sync? maybe important especially when the names aren't identical

2021-10-05 15:47 UTC, yinonov approved these changes

2021-10-06 04:26 UTC, merged