fix(text): tight option
Vonage/vivid pull request #1110
Opened 2021-10-28 15:46 UTC by rachelbt

- added a tight option for titles with no margin needed
- fixed the login example

2021-11-01 09:25 UTC, yinonov commented on components/text/src/vwc-text-base.ts
> +	tight = false;
```suggestion
		tight = false;
```

2021-11-01 09:53 UTC, yinonov requested changes
@rachelbt the text snapshot is updated here so once merged, it will remove the buttons' PR difference of that snapshot

2021-11-01 09:53 UTC, yinonov commented on components/text/readme.md
> +| `noSpacing` | `noSpacing` | `boolian` |
```suggestion
| `noSpacing` | `noSpacing` | `boolean` |
```

2021-11-01 09:53 UTC, yinonov commented on components/text/src/vwc-text-base.ts
> +			['tight']: !!this.tight,
```suggestion
			tight: this.tight,
```

2021-11-05 07:18 UTC, yinonov commented on components/text/readme.md
> +| `noSpacing` | `noSpacing` | `boolean` |
@rachelbt how does flat sound? really struggling here 😝

2021-11-07 12:01 UTC, rachelbt commented
don't think fat is right. I think we should either use tight yo noSpacing

2021-11-10 14:12 UTC, yinonov commented on components/text/readme.md
> +| `noSpacing` | `noSpacing` | `boolean` |
```suggestion
| `tight` | `tight` | `boolean` |
```

2021-11-10 14:13 UTC, yinonov approved these changes

2021-11-11 11:25 UTC, merged