Viv 1151 side drawer refactor
Vonage/vivid pull request #1172
Opened 2021-12-27 12:07 UTC by rinaok

2021-12-27 12:12 UTC, rinaok commented on components/side-drawer/src/vwc-side-drawer.scss
@yinonov @rachelbt Perhaps we can refactor the lines here since the default type is now dismissible.

2021-12-27 12:15 UTC, rinaok commented
@yinonov @rachelbt Perhaps we can refactor the **vwc-side-drawer.scss** since the default type is now dismissible.

2021-12-27 15:21 UTC, yinonov commented
> @yinonov @rachelbt Perhaps we can refactor the **vwc-side-drawer.scss** since the default type is now dismissible.

yes we should. will review

2021-12-28 19:07 UTC, yinonov requested changes
- [ ] refactor _type_ property to a _modal_ boolean only as it's dismissible by default
- [ ] take into account the semantic meaning of a modal drawer and what it means in an aria context

2021-12-29 11:44 UTC, rinaok commented
> * [ ]  refactor _type_ property to a _modal_ boolean only as it's dismissible by default
> * [ ]  take into account the semantic meaning of a modal drawer and what it means in an aria context

@yinonov If I'll change the _type_ property it will break for users.

2021-12-29 13:59 UTC, yinonov commented
> > * [ ]  refactor _type_ property to a _modal_ boolean only as it's dismissible by default
> 
> > * [ ]  take into account the semantic meaning of a modal drawer and what it means in an aria context
> 
> 
> 
> @yinonov If I'll change the _type_ property it will break for users.

Is the component GA?

2022-01-05 15:19 UTC, yinonov commented
@rinaok can we progress on this?

2022-01-06 15:52 UTC, rinaok commented
> > > * [x]   refactor _type_ property to a _modal_ boolean only as it's dismissible by default
> > 
> > 
> > > * [ ]   take into account the semantic meaning of a modal drawer and what it means in an aria context
> > 
> > 
> > @yinonov If I'll change the _type_ property it will break for users.
> 
> Is the component GA? If so, tag _type_ as deprecated and support both patterns

No, it's still Alpha

2022-01-17 11:28 UTC, yinonov requested changes

2022-01-17 11:28 UTC, yinonov commented on __snapshots__/side-drawer.md
> +<aside class="side-drawer side-drawer-dismissible">
if it's dismissible by default why do we need its class?
for style appliance just do something like
```css
.side-drawer:not(.side-drawer-modal) {
  /* dismissible content here */
}
```

2022-01-17 11:28 UTC, yinonov commented on components/side-drawer/src/vwc-side-drawer-base.ts
> +			'side-drawer-dismissible': !this.modal,
redundant

2022-01-18 14:02 UTC, rachelbt reviewed
CSS looks great :)

2022-01-19 10:16 UTC, yinonov requested changes
notice the difference in the `aside`'s position

##### production
![image](https://user-images.githubusercontent.com/15140652/150110586-6965cab7-2423-47d5-bb48-5df25c4ddcb4.png)

##### this PR
![image](https://user-images.githubusercontent.com/15140652/150110706-4757cb86-7e90-4c67-89e0-a6b1660343b3.png)

2022-01-19 13:16 UTC, rinaok commented
> 

@rachelbt Do you know why it happened?

2022-01-20 06:45 UTC, rachelbt commented on components/side-drawer/src/vwc-side-drawer.scss
> +	top: 0;
```suggestion
	top: auto;
```
this will fix the overlapping top bar and the side drawer

2022-01-21 08:54 UTC, yinonov requested changes

2022-01-21 08:54 UTC, yinonov commented on components/side-drawer/src/vwc-side-drawer-base.ts
> +	 * @prop modal - if side drawer is modal
```suggestion
	 * @prop modal - sets the type of the side drawer's to modal
```

2022-01-21 08:54 UTC, yinonov commented on components/side-drawer/src/vwc-side-drawer.scss
> +	transform: translateX(0%);
is this really required? isn't it set by default?

2022-01-23 13:40 UTC, yinonov approved these changes

2022-01-23 14:37 UTC, merged