fix(elevation): remove containment
Vonage/vivid pull request #1188
Opened 2022-01-04 13:23 UTC by rachelbt

`contain: content` causes nested components to be un-shown.
added ::slotted(*) for border-radius inherit (inherit doesn't)

2022-01-05 10:04 UTC, rachelbt commented
I think its better that there will be a case of missing border-radius rather then hidden content

2022-01-05 15:17 UTC, yinonov reviewed
maybe we can remove border-radius on elevation altogether?

2022-01-06 06:48 UTC, rachelbt commented
> 

It does :)

2022-01-06 16:31 UTC, yinonov requested changes
I think we can just remove the border radius from elevation as drop-shadow will take into consideration the shape of content.
So we leave shaping responsibility to

2022-01-06 16:31 UTC, yinonov commented on components/elevation/src/vwc-elevation.scss
>  }
what if it's just an icon or text that will be assigned to slot?
this is unexpected as we have no control over the content.

need to brain storm again

2022-01-09 09:28 UTC, yinonov commented on components/elevation/src/vwc-elevation.scss
> +	border-radius: var(#{$vvd-elevation-border-radius}, 6px);
```suggestion
```

2022-01-09 09:29 UTC, yinonov approved these changes

2022-01-09 09:38 UTC, merged