Chore(tooltip): new component
Vonage/vivid pull request #1223
Opened 2022-01-30 15:17 UTC by rachelbt

Clean and functunal tooltip.
Uses the popup component.
No need to review the popup changes :)

2022-01-30 22:14 UTC, yinonov reviewed
A tooltip provides additional information about an interacted target. It's commonly shown on mouse hover or focus. Do not target non-interactive controls as a tooltip's anchor (such as non-focusable / disabled elements). The absence of user interaction will prevent the tooltip from showing up.

Note that touch screen devices do not share the same pointer input events and may fail to show anything.

Consider avoiding the use of tooltip as it may fail to produce the same UX for ALL users. if must, contemplate on practices such as _aria-describedby_ to add alternative experience to users who aren't able to interact with a control in the same manner as sighted users

2022-02-01 13:17 UTC, rinaok commented on components/tooltip/src/vwc-tooltip-base.ts
> +	 * @prop content - the content of the tooltip
```suggestion
	 * @prop text - the text of the tooltip
```

2022-02-01 13:17 UTC, rinaok commented on components/tooltip/src/vwc-tooltip-base.ts
> +	 * @prop open - indicates whether the tip is open
```suggestion
	 * @prop open - indicates whether the tooltip is open
```

2022-02-01 13:18 UTC, rinaok commented on components/tooltip/src/vwc-tooltip-base.ts
> +	 * accepts boolean value
```suggestion
	 * accepts boolean value
	  * @public
```

2022-02-01 13:19 UTC, rinaok commented on components/tooltip/src/vwc-tooltip-base.ts
> +	 * Closes the popup
```suggestion
	 * Closes the tooltip
```

2022-02-01 13:19 UTC, rinaok commented on components/tooltip/src/vwc-tooltip-base.ts
> +	 * Opens the popup
```suggestion
	 * Opens the tooltip
```

2022-02-01 13:25 UTC, rinaok commented
<img width="485" alt="Screen Shot 2022-02-01 at 15 25 12" src="https://user-images.githubusercontent.com/10883919/151976569-86fd8c08-2689-49c7-8db8-ff94623eab2d.png">

2022-02-01 13:29 UTC, rinaok commented
Except for the UI test, there are no other tests.

2022-02-01 13:40 UTC, rinaok requested changes
Except for the UI test, there are no other tests.

2022-02-01 15:01 UTC, rachelbt commented
> <img alt="Screen Shot 2022-02-01 at 15 25 12" width="485" src="https://user-images.githubusercontent.com/10883919/151976569-86fd8c08-2689-49c7-8db8-ff94623eab2d.png">

there is not such a long word - if there to be longer text it will break into lines:
![image](https://user-images.githubusercontent.com/7512792/151993140-8c55cf38-7941-4f62-8f7e-dca1bd8fb1d2.png)

2022-02-01 15:10 UTC, rachelbt commented
> A tooltip provides additional information about an interacted target. It's commonly shown on mouse hover or focus. Do not target non-interactive controls as a tooltip's anchor (such as non-focusable / disabled elements). The absence of user interaction will prevent the tooltip from showing up.
> 
> Note that touch screen devices do not share the same pointer input events and may fail to show anything.
> 
> Consider avoiding the use of tooltip as it may fail to produce the same UX for ALL users. if must, contemplate on practices such as _aria-describedby_ to add alternative experience to users who aren't able to interact with a control in the same manner as sighted users

Added to the readme - separated some of the text.

2022-02-08 15:45 UTC, rinaok commented
> Except for the UI test, there are no other tests.

@rachelbt I still don't see a `test` folder inside tooltip folder.

2022-02-08 15:46 UTC, rinaok requested changes
@rachelbt I still don't see a test folder inside tooltip folder.

2022-02-09 16:13 UTC, rinaok submitted a review, later dismissed

2022-02-09 19:13 UTC, yinonov requested changes

2022-02-09 19:13 UTC, yinonov commented on components/tooltip/stories/tooltip.stories.js
> +export const InText = InsideTExtTemplate.bind({});
```suggestion
export const InText = InsideTextTemplate.bind({});
```

2022-02-09 19:13 UTC, yinonov commented on components/tooltip/stories/tooltip.stories.js
> +export const InATitle = AfterATitleTemplate.bind({});
```suggestion
export const InATitle = AfterTitleTemplate.bind({});
```

2022-02-09 19:13 UTC, yinonov commented on components/tooltip/stories/tooltip.stories.js
> +const AfterATitleTemplate = args => html`
```suggestion
const AfterTitleTemplate = args => html`
```

2022-02-10 07:18 UTC, yinonov approved these changes

2022-02-13 15:02 UTC, rinaok approved these changes

2022-02-13 15:08 UTC, merged