fix(menu): background and shadow colors
Vonage/vivid pull request #1280
Opened 2022-04-10 13:22 UTC by rachelbt

2022-04-10 13:32 UTC, rachelbt commented
@jshenkman 
menu: https://tmp.dev.vivid.vonage.com/1280/index.html?path=/story/components-menu--with-vwc-list-item
dropdown: https://tmp.dev.vivid.vonage.com/1280/index.html?path=/story/alpha-components-dropdown--basic&args=corner:BOTTOM_START

2022-04-10 14:47 UTC, jshenkman commented
> @jshenkman menu: https://tmp.dev.vivid.vonage.com/1280/index.html?path=/story/components-menu--with-vwc-list-item dropdown: https://tmp.dev.vivid.vonage.com/1280/index.html?path=/story/alpha-components-dropdown--basic&args=corner:BOTTOM_START

LGTM!! 🤩😍

2022-04-11 03:45 UTC, yinonov requested changes

2022-04-11 03:45 UTC, yinonov commented on components/surface/src/vwc-surface.scss
> +		background-color: var(--vvd-color-surface-8dp);
Change to sass const?

2022-04-11 03:45 UTC, yinonov commented on components/surface/src/vwc-surface.scss
> +		filter: var(--vvd-shadow-surface-8dp);
Same here

2022-04-26 20:20 UTC, yinonov requested changes
should select be scoped to this fix

<img width="302" alt="image" src="https://user-images.githubusercontent.com/15140652/165385192-09163e9c-db7b-41bd-97f8-d9145cae9ea9.png">

2022-04-27 08:38 UTC, rachelbt commented
> should select be scoped to this fix
> 
> <img alt="image" width="302" src="https://user-images.githubusercontent.com/15140652/165385192-09163e9c-db7b-41bd-97f8-d9145cae9ea9.png">

basically yes - the problem is that in the select we are using the `mwc-menu-surface` and not the vivid one.
If this need to be fixed - its a different task for my opinion

2022-05-04 07:06 UTC, yinonov approved these changes

2022-05-04 07:10 UTC, yinonov requested changes
checking

2022-05-04 07:26 UTC, yinonov approved these changes

2022-05-04 10:32 UTC, merged