feat(vwc-audio): audio disabled state (VIV-873)
Vonage/vivid pull request #1386
Opened 2023-04-02 08:41 UTC by YonatanKra

2023-04-10 13:26 UTC, rinaok requested changes
I have a` cursor="pointer" `while disabled

2023-04-10 13:58 UTC, YonatanKra commented on components/audio/src/vwc-audio.scss
> +				pointer-events: none;
```suggestion
				pointer-events: none;
				cursor: not-allowed;
```

2023-04-10 13:59 UTC, YonatanKra commented
> I have a`cursor="pointer"`while disabled

@rinaok 
Added `cursor: not-allowed;`

2023-04-11 08:15 UTC, rinaok approved these changes

2023-04-13 18:53 UTC, rachelbt approved these changes

2023-04-14 06:17 UTC, merged